check pods log and fix wrong exit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -184,19 +184,21 @@ jobs:
       - run:
           name: smoke test
           command: |
-              URL=$(cat url.txt)
-              PORT=80
-              ENDPOINT="${URL}:${PORT}/predict"
-              echo "Endpoint: ${ENDPOINT}"
-              RES=$(bash make_prediction.sh $URL $PORT | grep -i -P '200|"prediction": ')
+            URL=$(cat url.txt)
+            PORT=80
+            ENDPOINT="${URL}:${PORT}/predict"
+            echo "Endpoint: ${ENDPOINT}"
+            RES=$(bash make_prediction.sh $URL $PORT | grep -i -P '200|"prediction": ')
 
-              if [[ $RES ]]; then
-                printf "Successful POST request"
-                exit 1;
-              else
-                printf "failed to make a POST request to ${ENDPOINT}"
-                exit 0;
-              fi
+            if [[ $RES ]]; then
+              printf "Successful POST request"
+              kubectl logs podname -c duytt10-capstone
+              exit 0;
+            else
+              printf "failed to make a POST request to ${ENDPOINT}"
+              exit 1;
+            fi
+        
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
